export default {
  language: "Romanian",
  chapters: [
    require('./1.json'),
    require('./2.json'),
    require('./3.json'),
    require('./4.json'),
    require('./5.json'),
    require('./6.json'),
    require('./7.json'),
    require('./8.json'),
    require('./9.json'),
    require('./10.json'),
    require('./11.json'),
    require('./12.json'),
    require('./13.json'),
    require('./14.json'),
    require('./15.json'),
    require('./16.json'),
    require('./17.json'),
    require('./18.json'),
    require('./19.json'),
    require('./20.json'),
    require('./21.json'),
    require('./22.json'),
    require('./23.json'),
    require('./24.json'),
    require('./25.json'),
    require('./26.json'),
    require('./27.json'),
    require('./28.json'),
    require('./29.json')
  ],
};
